# Generated by Django 5.1.5 on 2025-12-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='access_code',
            field=models.CharField(blank=True, editable=False, max_length=5),
        ),
    ]
