# Generated by Django 5.1.5 on 2025-12-19 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='registration',
            name='phone_digits',
            field=models.CharField(default='', editable=False, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='access_code',
            field=models.CharField(editable=False, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('WAITLIST', 'Waitlist'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled'), ('REMOVED', 'Removed by organizer')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled'), ('REMOVED', 'Removed'), ('MOVED', 'Moved list')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='games.game')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.registration')),
            ],
        ),
    ]
